name: "CHEM IO"
description: "Community for material science enthusiasts, professional chemist and engineers."

author: "Alexi Ned"

url: "http://chemio.github.io"
baseurl: ""

markdown: rdiscount
permalink: :year/:month/:title.html
pygments: true

# Google Analytics
ga_domain: chemio.github.io
ga_tracking_id: UA-48888764-1
